packages:
  - apps/*
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true

overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.12
  fast-uri: 3.1.6
  hono: 4.13.5
  js-yaml@3: 3.15.2
  qs: 6.16.0
